name: BlissGems
version: 'dev'
main: com.hyperdondon.blissgemsremake.BlissGems
description: §x§f§f§e§4§a§b§lBlissGemsRemake §fby §4Hyper_Dondon §band §0Cupm §f(Original by Pro4D)
api-version: '1.17'
authors:
  - Hyper_Dondon
  - Cupm
commands:
  blissgems:
    aliases: bliss
    description: Main command for BlissGems
    usage: /<command>

  progression:
    description: Command for progression
    usage: /<command>

  progobsidian:
    description: Gives the player enchanted obsidian
    usage: /<command>

libraries:
  - org.openjdk.nashorn:nashorn-core:15.4
  - org.mariadb.jdbc:mariadb-java-client:3.0.3
  - com.mysql:mysql-connector-j:9.0.0
  - org.xerial:sqlite-jdbc:3.46.0.0